version: "3.3"
services:
  pg:
    image: postgres
    container_name: url-shortener-pg
    restart: always
    ports:
      - '${PG_PORT}:5432'
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
